language: go
go:
  - 1.5.4
  - 1.6.2
env:
  - GOARCH: amd64
  - GOARCH: 386
addons:
  hosts:
    - api.openweathermap.org
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email:
    recipients:
      - brian.downs@gmail.com
    on_success: change
    on_failure: always
    after_success:
      - coveralls
